server:
  port: 8501
spring:
  application:
    name: server-manager
  datasource:
    url: jdbc:mysql://192.168.233.137:3306/db_fhr_shopping?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  redis:
    host: 192.168.233.137
    port: 6379
    password: 123456
    database: 2

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

shopping:
  minio:
    endpointUrl: http://192.168.233.137:9000
    accessKey: admin
    secretKey: 12345678
    bucketName: fhr-shopping
